In [12]:
import numpy as np
import pandas as pd

### Numpy

#### 1. Создание массивов

In [13]:
# Создание массива из списка
l = [1, 2, 3, 4, 5]
arr1 = np.array(l)

# Создание двумерного массива
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("arr1:", arr1)
print("arr2:\n", arr2)
print('arr2.shape:', arr2.shape)

arr1: [1 2 3 4 5]
arr2:
 [[1 2 3]
 [4 5 6]]
arr2.shape: (2, 3)


In [14]:
print("len:", len(arr2), "-- количество элементов по первой оси.",
      "\nsize:", arr2.size, "-- всего элементов в матрице.",
      "\nndim:", arr2.ndim, "-- размерность матрицы.",
      "\nshape:", arr2.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 6 -- всего элементов в матрице. 
ndim: 2 -- размерность матрицы. 
shape: (2, 3) -- количество элементов по каждой оси.


In [15]:
# Создание массива с нулями
zeros = np.zeros((3, 4))

# Создание массива с единицами
ones = np.ones((2, 3))

print("zeros:\n", zeros)
print("ones:\n", ones)

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Создание массива с заданным шагом
range_arr = np.arange(0, 10, 2)

# Создание массива случайных чисел
random_arr = np.random.rand(3, 3)

print("range_arr:", range_arr)
print("random_arr:\n", random_arr)

range_arr: [0 2 4 6 8]
random_arr:
 [[0.03425597 0.28778721 0.08817966]
 [0.98784688 0.2638973  0.87277304]
 [0.34489747 0.53624586 0.09620135]]


In [17]:
a = np.linspace(1, 15, 4)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1.          5.66666667 10.33333333 15.        ]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


#### 2. Операции с массивами

In [18]:
# Арифметические операции
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)
print("a * b =", a * b)
print("a ** 2 =", a ** 2)

a + b = [5 7 9]
a * b = [ 4 10 18]
a ** 2 = [1 4 9]


In [19]:
# Статистические функции
print("Среднее значение a:", np.mean(a))
print("Стандартное отклонение b:", np.std(b))
print("Сумма элементов a:", np.sum(a))

Среднее значение a: 2.0
Стандартное отклонение b: 0.816496580927726
Сумма элементов a: 6


In [20]:
# Операции с матрицами
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Умножение матриц:\n", np.dot(m1, m2))
print("Транспонирование m2:\n", m2.T)
print("Умножение матриц:\n", np.dot(m1, m2.T))

Умножение матриц:
 [[19 22]
 [43 50]]
Транспонирование m2:
 [[5 7]
 [6 8]]
Умножение матриц:
 [[17 23]
 [39 53]]


#### 3. Индексация

In [21]:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

print("arr:\n", arr)
print("Первая строка:", arr[0])
print("Второй столбец:", arr[:, 1])
print("Подмассив:\n", arr[0:3, 1:3])


arr:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Первая строка: [1 2 3 4]
Второй столбец: [ 2  6 10]
Подмассив:
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [22]:
# Indexing
# Условная индексация
condition = arr > 25
print("Условная индексация:", arr[condition])

# Индексация с помощью массива булевых значений
mask = np.array([True, False, True, False, True])
print("Индексация с маской:", arr[mask])

Условная индексация: []


IndexError: boolean index did not match indexed array along axis 0; size of axis is 3 but size of corresponding boolean axis is 5

In [ ]:
# Изменение формы
reshaped = arr.reshape(2, -1)
print("Измененная форма:\n", reshaped)
print('reshaped.shape', reshaped.shape)

Измененная форма:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
reshaped.shape (2, 6)


In [ ]:
#Sorting
sorted_arr = np.sort(arr)
sorted_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Суммирование по осям
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Сумма по строкам:", np.sum(arr_2d, axis=1))
print("Сумма по столбцам:", np.sum(arr_2d, axis=0))


arr_2d
 [[1 2 3]
 [4 5 6]]
Сумма по строкам: [ 6 15]
Сумма по столбцам: [5 7 9]
Вертикальная конкатенация:
 [[1 2]
 [3 4]
 [5 6]]
Горизонтальная конкатенация:
 [[1 2 5]
 [3 4 6]]


In [23]:
# Конкатенация массивов

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("Вертикальная конкатенация:\n", np.concatenate((a, b), axis=0))
print("Горизонтальная конкатенация:\n", np.concatenate((a, b.T), axis=1))

Вертикальная конкатенация:
 [[1 2]
 [3 4]
 [5 6]]
Горизонтальная конкатенация:
 [[1 2 5]
 [3 4 6]]


In [24]:
c = np.array([[5, 6, 7], [7, 8, 9]])
np.concatenate((a, c), axis=1)

array([[1, 2, 5, 6, 7],
       [3, 4, 7, 8, 9]])

In [25]:
# Применение функций к каждому элементу
arr = np.array([-4, -2, 3, 2, 4])
print("Абсолютные значения:", np.abs(arr))
print(" ")
print("Экспонента:", np.exp(arr))
print(" ")
print("Логарифм:", np.log(np.abs(arr)))


Абсолютные значения: [4 2 3 2 4]
 
Экспонента: [1.83156389e-02 1.35335283e-01 2.00855369e+01 7.38905610e+00
 5.45981500e+01]
 
Логарифм: [1.38629436 0.69314718 1.09861229 0.69314718 1.38629436]


In [26]:
# Генерация случайных чисел
random_ints = np.random.randint(0, 10, size=(3, 3))
print("Случайные целые числа:\n", random_ints)

# Нормальное распределение
normal_dist = np.random.normal(loc=0, scale=1, size=(1000,))
print("Среднее нормального распределения:", np.mean(normal_dist))
print("Стандартное отклонение:", np.std(normal_dist))

# Равномерное распределение
uniform_dist = np.random.uniform(low=0, high=1, size=(1000,))
print("Минимум равномерного распределения:", np.min(uniform_dist))
print("Максимум:", np.max(uniform_dist))

Случайные целые числа:
 [[5 6 7]
 [8 1 4]
 [0 0 1]]
Среднее нормального распределения: 0.002297901230012968
Стандартное отклонение: 0.9815455108798011
Минимум равномерного распределения: 4.785730837242319e-05
Максимум: 0.9985943196324188


In [27]:
# Создание массива с пропущенными значениями
arr_with_nan = np.array([1, 2, np.nan, 4, 5])
print("Массив с NaN:", arr_with_nan)

# Проверка на NaN
print("Есть ли NaN?", np.isnan(arr_with_nan))


Массив с NaN: [ 1.  2. nan  4.  5.]
Есть ли NaN? [False False  True False False]


In [28]:
# Замена NaN на среднее значение
mean_value = np.nanmean(arr_with_nan)
arr_without_nan = np.where(np.isnan(arr_with_nan), mean_value, arr_with_nan)
print("Массив после замены NaN:", arr_without_nan)

Массив после замены NaN: [1. 2. 3. 4. 5.]
