In [1]:
import numpy as np
import pandas as pd

In [10]:
l=[1,2,3]
arr1 = np.array(l)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("arr1:", arr1)
print("arr2:\n", arr2)
print("arr2.shape:", arr2.shape)

arr1: [1 2 3]
arr2:
 [[1 2 3]
 [4 5 6]]
arr2.shape: (2, 3)


In [12]:
print("len:", len(arr2),
      "\nsize:", arr2.size,
      "\ndimension:", arr2.ndim,
      "\nshape:", arr2.shape)

len: 2 
size: 6 
dimension: 2 
shape: (2, 3)


In [17]:
zeros = np.zeros((2,3))
ones= np.ones((3,4))
print("zeros:",zeros)
print("ones:\n", ones)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
range_arr = np.arange(0,10,3)
random = np.random.rand(2,3)
print(range_arr)
print(random)


[0 3 6 9]
[[0.75307296 0.0345254  0.37398926]
 [0.1338147  0.60513037 0.87759804]]
